### ISSUE TITLE
Fork this repo needs a link in lets_code.md

### ISSUE THREAD

**Issue by davidmweber** [codex-academy/codeX_Setup_Intro#1]
I assume the 53 functions are a kata from somewhere. I think there should be a link?

**Comment by avermeulen** [comment]
What do you mean?

I thought it all out mainly...

André

**Comment by davidmweber** [comment]
Ok. Good thinking. Fun problems :)  I was thinking there was a  template with a testing framework in place? Here is an example of one I did in Scala: https://github.com/8eo/puzzle_time with solutions at https://github.com/8eo/puzzle_solutions
